# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classifier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10\x63lassifier.proto\">\n\x15\x43lassificationRequest\x12%\n\x15\x63lassificationRequest\x18\x01 \x03(\x0b\x32\x06.Image\"L\n\x13\x43lassificationReply\x12\x35\n\x16\x63lassificationResponse\x18\x01 \x03(\x0b\x32\x15.ClassificatioMessage\"\'\n\x05Image\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nchunk_data\x18\x02 \x01(\x0c\"2\n\x14\x43lassificatioMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t2Q\n\nClassifier\x12\x43\n\x11GetClassification\x12\x16.ClassificationRequest\x1a\x14.ClassificationReply\"\x00\x62\x06proto3'
)




_CLASSIFICATIONREQUEST = _descriptor.Descriptor(
  name='ClassificationRequest',
  full_name='ClassificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classificationRequest', full_name='ClassificationRequest.classificationRequest', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=82,
)


_CLASSIFICATIONREPLY = _descriptor.Descriptor(
  name='ClassificationReply',
  full_name='ClassificationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='classificationResponse', full_name='ClassificationReply.classificationResponse', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=160,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Image.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_data', full_name='Image.chunk_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=201,
)


_CLASSIFICATIOMESSAGE = _descriptor.Descriptor(
  name='ClassificatioMessage',
  full_name='ClassificatioMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ClassificatioMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='ClassificatioMessage.result', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=253,
)

_CLASSIFICATIONREQUEST.fields_by_name['classificationRequest'].message_type = _IMAGE
_CLASSIFICATIONREPLY.fields_by_name['classificationResponse'].message_type = _CLASSIFICATIOMESSAGE
DESCRIPTOR.message_types_by_name['ClassificationRequest'] = _CLASSIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['ClassificationReply'] = _CLASSIFICATIONREPLY
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['ClassificatioMessage'] = _CLASSIFICATIOMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassificationRequest = _reflection.GeneratedProtocolMessageType('ClassificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONREQUEST,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ClassificationRequest)
  })
_sym_db.RegisterMessage(ClassificationRequest)

ClassificationReply = _reflection.GeneratedProtocolMessageType('ClassificationReply', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIONREPLY,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ClassificationReply)
  })
_sym_db.RegisterMessage(ClassificationReply)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:Image)
  })
_sym_db.RegisterMessage(Image)

ClassificatioMessage = _reflection.GeneratedProtocolMessageType('ClassificatioMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLASSIFICATIOMESSAGE,
  '__module__' : 'classifier_pb2'
  # @@protoc_insertion_point(class_scope:ClassificatioMessage)
  })
_sym_db.RegisterMessage(ClassificatioMessage)



_CLASSIFIER = _descriptor.ServiceDescriptor(
  name='Classifier',
  full_name='Classifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=255,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetClassification',
    full_name='Classifier.GetClassification',
    index=0,
    containing_service=None,
    input_type=_CLASSIFICATIONREQUEST,
    output_type=_CLASSIFICATIONREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFIER)

DESCRIPTOR.services_by_name['Classifier'] = _CLASSIFIER

# @@protoc_insertion_point(module_scope)
