# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import classifier_pb2 as classifier__pb2


class ClassifierStub(object):
    """The classifier service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClassification = channel.unary_unary(
                '/Classifier/GetClassification',
                request_serializer=classifier__pb2.ClassificationRequest.SerializeToString,
                response_deserializer=classifier__pb2.ClassificationReply.FromString,
                )


class ClassifierServicer(object):
    """The classifier service definition.
    """

    def GetClassification(self, request, context):
        """Sends a classification
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClassification': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClassification,
                    request_deserializer=classifier__pb2.ClassificationRequest.FromString,
                    response_serializer=classifier__pb2.ClassificationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Classifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Classifier(object):
    """The classifier service definition.
    """

    @staticmethod
    def GetClassification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Classifier/GetClassification',
            classifier__pb2.ClassificationRequest.SerializeToString,
            classifier__pb2.ClassificationReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
